apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml
  - certificates/argocd.yaml
  - certificates/vault.yaml
  - certificates/bbox.yaml
  - certificates/jellyfin.yaml
