apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml
  - certificates/argocd.yaml
  - certificates/vault.yaml
  - certificates/bbox.yaml
  - certificates/media.yaml
  - certificates/nextcloud.yaml
  - certificates/radarr.yaml
  - certificates/sonarr.yaml
  - certificates/jackett.yaml
  - certificates/qbittorrent.yaml
  - certificates/flood.yaml
