---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`series.media.armleth.fr`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      services:
        - name: authentik-server
          namespace: authentik
          port: 80
    - match: Host(`series.media.armleth.fr`)
      kind: Rule
      priority: 10
      services:
        - name: sonarr-service
          port: 8989
      middlewares:
        - name: authentik-forward-auth
          namespace: authentik
        - name: arr-local-client-ip
  tls:
    secretName: sonarr-tls-secret
