---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd
            port:
              number: 80
