---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actual-budget-oidc
  namespace: actual-budget
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: actual-budget-oidc
    template:
      data:
        ACTUAL_OPENID_CLIENT_SECRET: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: secret/actual-budget
        property: oidc-client-secret
