apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/armleth/richelieu.git
    targetRevision: HEAD
    path: k8s/apps/argocd
  destination:
    name: in-cluster
    namespace: argocd
