apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bbox
  namespace: keycloak
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/lucassiauve/tmp_infra.git
    targetRevision: HEAD
    path: k8s/apps/bbox
  destination:
    name: in-cluster
    namespace: keycloak
