apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.1
    helm:
      values: |
        crds:
          enabled: true
        cainjector:
          extraArgs:
            - --namespace=cert-manager
            - --enable-certificates-data-source=false
          extraEnv:
            - name: MALLOC_ARENA_MAX
              value: "2"
          resources:
            requests:
              memory: 16Mi
            limits:
              memory: 48Mi
        extraEnv:
          - name: MALLOC_ARENA_MAX
            value: "2"
        resources:
          requests:
            memory: 24Mi
          limits:
            memory: 48Mi
        webhook:
          extraEnv:
            - name: MALLOC_ARENA_MAX
              value: "2"
          resources:
            requests:
              memory: 16Mi
            limits:
              memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
