apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: keycloak
    targetRevision: 25.2.0
    helm:
      values: |
        production: true
        proxyHeaders: xforwarded
        httpRelativePath: /
        auth:
          adminUser: admin
        postgresql:
          enabled: true
        service:
          type: ClusterIP
          ports:
            http: 80
        tls:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
