apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: vault
spec:
  project: default
  sources:
    - repoURL: https://github.com/armleth/richelieu.git
      targetRevision: HEAD
      path: k8s/apps/vault
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.28.0
      helm:
        releaseName: vault
        values: |
          server:
            ha:
              enabled: true
              replicas: 1

            dataStorage:
              enabled: true
              size: 10Gi
              storageClass: standard

            extraConfig: |
              ui = true
              listener "tcp" {
                address     = "0.0.0.0:8200"
                tls_disable = 1
              }
              storage "raft" {
                path = "/vault/data"
              }
              service_registration "kubernetes" {}

            readinessProbe:
              enabled: true
              path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"

            livenessProbe:
              enabled: true
              path: "/v1/sys/health?standbyok=true"
              initialDelaySeconds: 60

            resources:
              requests:
                memory: 128Mi
                cpu: 125m
              limits:
                memory: 256Mi
                cpu: 250m

            extraEnvironmentVars:
              VAULT_ADDR: "http://127.0.0.1:8200"

            service:
              enabled: true
              type: ClusterIP
              port: 8200

            ingress:
              enabled: false

            affinity: {}
            tolerations: []
            
          injector:
            enabled: false
          csi:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
