apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: vault
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/armleth/richelieu.git
    targetRevision: HEAD
    path: k8s/apps/vault
  destination:
    name: in-cluster
    namespace: vault
