apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/armleth/richelieu_try.git
    targetRevision: HEAD
    path: k8s/apps/vault-config
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
