apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: vault
spec:
  project: default
  sources:
    - repoURL: https://github.com/armleth/richelieu.git
      targetRevision: HEAD
      path: k8s/apps/vault
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.30.0
      helm:
        releaseName: vault
        values: |
          global:
            tlsDisable: true
          server:
            enabled: true
            sandalone:
              enabled: true
              config: |
                ui = true
                disable_mlock = true

                listener "tcp" {
                  address     = "0.0.0.0:8200"
                  tls_disable = 1
                }

                storage "file" {
                  path = "/vault/data"
                }

            dataStorage:
              enabled: true
              size: 10Gi
              storageClass: local-path

            readinessProbe:
              enabled: true
              path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"

            livenessProbe:
              enabled: true
              path: "/v1/sys/health?standbyok=true"
              initialDelaySeconds: 60

            resources:
              requests:
                memory: 128Mi
                cpu: 125m
              limits:
                memory: 256Mi
                cpu: 250m

          injector:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
