apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
    spec:
      containers:
        - name: authentik
          image: ghcr.io/goauthentik/server:2024.12
          args: ["worker"]
          env:
            - name: AUTHENTIK_WORKER__CONCURRENCY
              value: "1"
            - name: AUTHENTIK_LOG_LEVEL
              value: "warning"
            - name: AUTHENTIK_DISABLE_UPDATE_CHECK
              value: "true"
            - name: AUTHENTIK_DISABLE_STARTUP_ANALYTICS
              value: "true"
            - name: AUTHENTIK_OUTPOSTS__DISCOVER
              value: "false"
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: authentik-pg-rw
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: "5432"
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-db-secret
                  key: password
            - name: AUTHENTIK_REDIS__HOST
              value: authentik-redis
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: secret-key
          resources:
            requests:
              memory: 200Mi
              cpu: 25m
            limits:
              memory: 500Mi
