apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secret
  data:
    - secretKey: admin-password
      remoteRef:
        key: secret/authentik
        property: admin-password
    - secretKey: secret-key
      remoteRef:
        key: secret/authentik
        property: secret-key
    - secretKey: db-password
      remoteRef:
        key: secret/authentik
        property: db-password
