apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-db-secret
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-db-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: authentik
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/authentik
        property: db-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-secret
  storage:
    size: 2Gi
  resources:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 128Mi
  postgresql:
    parameters:
      shared_buffers: "32MB"
      max_connections: "10"
      max_parallel_workers: "1"
      max_worker_processes: "2"
      max_parallel_workers_per_gather: "1"
      max_parallel_maintenance_workers: "1"
      work_mem: "2MB"
      maintenance_work_mem: "16MB"
      effective_cache_size: "64MB"
      wal_keep_size: "32MB"
