---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.armleth.fr`)
      services:
        - name: keycloak
          port: 8080
  tls:
    secretName: armleth-tls-secret
