apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin-secret.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  - external-secret-argocd-oidc.yaml
