apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-db-secret
    template:
      data:
        username: keycloak
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/keycloak
        property: db-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-pg
  namespace: keycloak
spec:
  instances: 1
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-secret
  storage:
    size: 2Gi
  resources:
    requests:
      memory: 96Mi
      cpu: 50m
    limits:
      memory: 192Mi
  postgresql:
    parameters:
      shared_buffers: "64MB"
      max_connections: "20"
      max_parallel_workers: "2"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "1"
      max_parallel_maintenance_workers: "1"
      work_mem: "4MB"
      maintenance_work_mem: "32MB"
      effective_cache_size: "128MB"
      wal_keep_size: "64MB"
