apiVersion: v1
kind: Secret
metadata:
  name: repo-docker-io
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  name: docker-io
  type: helm
  url: registry-1.docker.io
