---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lathibandolaise-app-secret
  namespace: lathibandolaise
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: lathibandolaise-app-secret
    template:
      data:
        DATABASE_URL: "postgres://lathibandolaise:{{ .password }}@lathibandolaise-pg-rw:5432/lathibandolaise"
  data:
    - secretKey: password
      remoteRef:
        key: secret/lathibandolaise
        property: db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lathibandolaise-ghcr-secret
  namespace: lathibandolaise
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: lathibandolaise-ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"{{ .pat }}"}}}'
  data:
    - secretKey: pat
      remoteRef:
        key: secret/lathibandolaise
        property: ghcr-pat
