---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lathibandolaise

resources:
  - postgres.yaml
  - external-secret.yaml
  - deployment-test.yaml
  - deployment-prod.yaml
  - service-test.yaml
  - service-prod.yaml
  - ingress.yaml
