---
apiVersion: v1
kind: Service
metadata:
  name: lathibandolaise-test-service
  namespace: lathibandolaise
spec:
  selector:
    app: lathibandolaise-test
  ports:
    - port: 8080
      targetPort: 8080
