---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - downloads-pvc.yaml
  - jellyfin/
  - radarr/
  - sonarr/
  - jackett/
  - flaresolverr/
  - qbittorrent/
  - flood/
