apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.armleth.fr
  accounts.admin.enabled: "true"
  timeout.reconciliation: "300s"
  resource.exclusions: |
    - apiGroups:
        - ""
      kinds:
        - "Events"
      clusters:
        - "*"
  oidc.config: |
    name: Authentik
    issuer: https://auth.armleth.fr/application/o/argocd/
    clientID: argocd
    clientSecret: $argocd-oidc-secret:oidc.authentik.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
