---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dbgate-app-secret
  namespace: lathibandolaise
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dbgate-app-secret
    template:
      data:
        USER_con1: "lathibandolaise"
        PASSWORD_con1: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/lathibandolaise
        property: db-password
