---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - external-secret.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
