---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server-git-secret
  namespace: code-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: code-server-git-secret
  data:
    - secretKey: token
      remoteRef:
        key: secret/lathibandolaise
        property: git-pat
