apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flood-tls
  namespace: media
spec:
  secretName: flood-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - downloads.media.armleth.fr
