apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karakeep-tls
  namespace: karakeep
spec:
  secretName: karakeep-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bookmarks.armleth.fr
