apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-tls
  namespace: media
spec:
  secretName: media-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - media.armleth.fr
