apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-tls
  namespace: media
spec:
  secretName: qbittorrent-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - torrents.media.armleth.fr
