apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unmanic-tls
  namespace: media
spec:
  secretName: unmanic-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - unmanic.media.armleth.fr
