---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: karakeep-secret
  namespace: karakeep
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: karakeep-secret
    template:
      data:
        NEXTAUTH_SECRET: "{{ .nextauthSecret }}"
        MEILI_MASTER_KEY: "{{ .meiliMasterKey }}"
        OAUTH_CLIENT_SECRET: "{{ .oidcClientSecret }}"
  data:
    - secretKey: nextauthSecret
      remoteRef:
        key: secret/karakeep
        property: nextauth-secret
    - secretKey: meiliMasterKey
      remoteRef:
        key: secret/karakeep
        property: meili-master-key
    - secretKey: oidcClientSecret
      remoteRef:
        key: secret/karakeep
        property: oidc-client-secret
