---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-secret
    template:
      data:
        client_secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: secret/grafana
        property: oidc-client-secret
