apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  dns01:
    email: armleth@proton.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
        cloudflare:
          email: armleth@proton.me
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: api-token
