---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bbox-proxy-config
  namespace: keycloak
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://192.168.1.254;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
