---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbox-proxy
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbox-proxy
  template:
    metadata:
      labels:
        app: bbox-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config
        configMap:
          name: bbox-proxy-config
