---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bbox-oidc-secret
  namespace: bbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bbox-oidc-secret
  data:
    - secretKey: client-secret
      remoteRef:
        key: secret/bbox
        property: oidc-client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: secret/bbox
        property: cookie-secret
