---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bbox
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`bbox.armleth.fr`)
      services:
        - name: bbox
          port: 443
  tls:
    secretName: armleth-tls-secret
