---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: box-ingressroute
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bbox.armleth.fr`)
      kind: Rule
      services:
        - name: box-proxy-service
          port: 80
  tls:
    secretName: armleth-tls-secret
