---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bbox-ingressroute
  namespace: bbox
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bbox.armleth.fr`)
      kind: Rule
      services:
        - name: bbox-proxy-service
          port: 80
  tls:
    secretName: bbox-tls

