---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bbox

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - secrets.yaml
  - service.yaml
  - cert-bbox.yaml
