---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-bbox
  namespace: keycloak
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecrets-bbox
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secretstore-bbox
    kind: SecretStore
  target:
    name: vault-armleth-tls-secret
    creationPolicy: Owner
  data:
  - secretKey: vault-armleth-tls-secret
    remoteRef:
      key: tls
      property: armleth
